# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonPyqgis
                                 A QGIS plugin
 un plugin 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-06
        copyright            : (C) 2025 by ENSG
        email                : thiriot2002@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MonPyqgis class from file MonPyqgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pyqgis_plugin import MonPyqgis
    return MonPyqgis(iface)
